server:
  port: 9100
management:
  port: 9101
  security:
    enabled: false
spring:
  application:
    name: TurbineServer
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
turbine:
#  cluster-name-expression: default
  combine-host-port: true
  app-config: UserService

