server:
  port: ${port:9000}
spring:
  application:
    name: ZipkinService
  sleuth:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.9:3306/zipkin?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: 123
    continue-on-error: true

zipkin:
  storage:
    type: mysql
#     elasticsearch:
#       hosts: "192.168.0.9:9200"
#       max-request: 64
#       index: zipkin
#       index-shard: 5

eureka:
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    statusPageUrlPath: ${management.context-path}/info
    appname: zipkin-server

management:
  security.enabled: false
  context-path: /