server:
  port: ${port:9002}
spring:
  application:
    name: MonitorServer
  boot:
    admin:
      discovery:
        ignored-services: MonitorServer
      routes.endpoints:
        env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      notify:
        mail:
          to: 1290650611@qq.com
          from: lrlzzch@163.com
          ignore-changes:
            -
              "*:UP" #从任何状态到up状态都不要发邮件通知
      turbine:
#        clusters: default
        enabled: true
#        location:


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    statusPageUrlPath: ${management.context-path}/info
    appname: MonitorServer

management:
  security:
    enabled: false
  context-path: /
  port: 9100
#endpoints:
#  pause:
#    sensitive: false
security:
  basic:
    enabled: false
  user:
    name: user
    password: user
turbine:
  cluster-name-expression: "default"
  app-config: UserService #,order-service,zipkin-server
  combine-host-port: true