server:
  port: 8761
  #nginx转发携带header
  use-forward-headers: true
eureka:
  instance:
    hostname: localhost
  server:
    #自我保护
    enable-self-preservation: true
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  environment: prod
spring:
  profiles:
    active: prod
management:
  security:
    enabled: false