server:
  port: 8761
management:
  context-path: /management
  security:
    enabled: false
spring:
  application:
    name: EurekaServer
--
spring:
  profiles: peer1

eureka:
  environment: production
  server:
    enableSelfPreservation: true
  instance:
    hostname: eureka-peer1                               # 指定当profile=peer1时，主机名
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer2:8761/eureka/
--
spring:
  profiles: peer2

eureka:
  environment: production
  server:
    enableSelfPreservation: true
  instance:
    hostname: eureka-peer2                               # 指定当profile=peer1时，主机名
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/
